mode: chatops
autoCloseIssue: true
branchName: ${issue.number}-${issue.title,}
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: question
    skip: true