name: checkstyle

on: pull_request

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          tool_name: checkstyle
          level: error
          checkstyle_version: 9.0.1
          checkstyle_config: ./config/checkstyle/checkstyle.xml
          properties_file: ./config/checkstyle
          fail_on_error: true
