name: checkstyle

on: pull_request

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-review'
          tool_name: 'checkstyle'
          checkstyle_version: '8.44'
          checkstyle_config: ./checkstyle.xml